<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <Optimize>true</Optimize>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Version>2.0.0.1</Version>
    <AssemblyVersion>2.0.0.1</AssemblyVersion>
    <FileVersion>2.0.0.1</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kangaroo.Core\Kangaroo.Core.csproj" />
  </ItemGroup>

</Project>
