<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Kangaroo.Core</AssemblyName>
    <Version>2.0.0.0</Version>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <FileVersion>2.0.0.0</FileVersion>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Title>Kangaroo.Core</Title>
    <Authors>BURGGASSER Philip</Authors>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>bin\Debug\net10.0\Kangaroo.Core.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>bin\Release\net10.0\Kangaroo.Core.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Implementations\**" />
    <EmbeddedResource Remove="Implementations\**" />
    <None Remove="Implementations\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kangaroo.Core.Interfaces\Kangaroo.Core.Interfaces.csproj" />
  </ItemGroup>

</Project>
